version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    links:
      - db

  db:
    image: mysql:5.7.21
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - 8080:80
    links:
      - db